import Head from "next/head";
import Admin from "./login";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <Admin />
    </div>
  );
}
