import Head from "next/head";

import Admin from "./login";

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Admin />
    </>
  );
}
