import Head from "next/head";
import Header from "../src/components/Header";
import Info from "../src/components/Info";
import Product from "./product";
import Infos from "./info";
import Contact from "../src/components/Contact/Contact";
import Footer from "../src/components/Contact/Footer";
export const getStaticProps = async () => {
  const res = await fetch("http://localhost:3000/api/header");

  // const productRes = await fetch('http://localhost:3000/api/product')
  const data = await res.json();
  // const productData = await productRes.json()
  return {
    // productData: productData
    props: { data },
  };
};
export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Sealjet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.jpg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
      </Head>

      <>
        <Header data={data[0]} />
        {/* <Product ismain={true} /> */}
        <div className="bg-zinc-100 pt-12">
          <h2 className="title text-2xl font-bold mx-auto px-4">
            Мэдээ, мэдээлэл
          </h2>
          {/* <Infos data={3} /> */}
        </div>
      </>
      <div id="contacts">
        {/* <Contact /> */}
        {/* <Footer /> */}
      </div>
    </div>
  );
}
