import Head from 'next/head'
import Header from '../src/components/Header'


export const getStaticProps = async () => {
  const res = await fetch('http://localhost:3000/api/header')
  const data = await res.json()
  return {
    props: { data: data }
  }
}
export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Sealjet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/sealjet-logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/> 
      </Head>

      <>
        <Header data={data}/>
      </>

    </div>
  )
}
